name: Check html

on:
  schedule:
    - cron: '00 0 * * *'

jobs:
  check:
    name: check
    runs-on: ubuntu-latest
    steps:
      - name: wget
        run: wget https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators -O index.html
