name: Check JSON diff

on:
  schedule:
    - cron: '00 0 * * *'
permissions:
  contents: write
  pull-requests: write


jobs:
  check:
    name: Check
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - run: rustup toolchain install stable --profile minimal

      - uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --verbose
      - name: Run
        run: echo CARGO_RUN_OUTPUT=$(cargo run) >> $GITHUB_ENV
      - name: Create commits
        if : contains(env.CARGO_RUN_OUTPUT, 'differ')
        run: |
          git config user.name '${{ github.actor }}'
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git add -A
          git commit -m "Update Json files"
      - name: Set current datetime as env variable
        env:
          TZ: 'Asia/Tokyo'
        run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
      - name: Create Pull Request
        if : contains(env.CARGO_RUN_OUTPUT, 'differ')
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update Json files
          title: Update Json files ${{ env.CURRENT_DATETIME }}
          body: Update Json files
          branch: update-json-files-${{ env.CURRENT_DATETIME }}
          base: main
          reviewers: |
            ${{ github.actor }}
          assignees: |
            ${{ github.actor }}
